#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

ynh_script_progression --message="Loading installation settings..." --time --weight=1

app=$YNH_APP_INSTANCE_NAME
domain=$(ynh_app_setting_get --app=$app --key=domain)
port=$(ynh_app_setting_get --app=$app --key=port)
final_path=$(ynh_app_setting_get --app=$app --key=final_path)

#=================================================
# REMOVE SERVICE INTEGRATION IN YUNOHOST
#=================================================

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_exec_warn_less yunohost service status $app >/dev/null
then
	ynh_script_progression --message="Removing $app service integration..." --time --weight=1
	yunohost service remove $app
fi

#=================================================
# STOP AND REMOVE SERVICE
#=================================================
ynh_script_progression --message="Stopping and removing the systemd service..." --time --weight=1

# Remove the dedicated systemd config
ynh_remove_systemd_config

#=================================================
# REMOVE NGINX CONF
#=================================================
ynh_script_progression --message="Removing NGINX web server configuration..." --time --weight=1
ynh_remove_nginx_config

#=================================================
# REMOVE FINAL PATH
#=================================================
ynh_script_progression --message="Removing $final_path..." --time --weight=1
ynh_secure_remove --file=$final_path

#=================================================
# REMOVE DOCKER VOLUMES
#=================================================
ynh_script_progression --message="Removing docker volumes ${app}_drone-data..." --time --weight=1
sudo docker volume rm ${app}_drone-data

#=================================================
# CLOSE A PORT
#=================================================

if yunohost firewall list | grep -q "\- $port$"
then
	ynh_script_progression --message="Closing port $port..." --time --weight=1
	ynh_exec_warn_less yunohost firewall disallow TCP $port
fi

#=================================================
# RELOAD NGINX
#=================================================
ynh_script_progression --message="Reloading NGINX web server..." --time --weight=1

ynh_systemd_action --service_name=nginx --action=reload

# TODO check if it is done automatically
ynh_permission_update --permission="main" --remove="visitors"

ynh_script_progression --message="Removal of $app completed" --time --last
